[package]
name = "conventional-commits-next-semver"
description = "A library for detecting the next semver version based on conventional-commits commit messages"
version = "0.0.0"
license = "MIT OR Apache-2.0"
authors = ["Sven Lechner <SirWindfield@users.noreply.github.com>"]
edition = "2018"
